### ISSUE TITLE
error line 1 ^ SyntaxError: invalid syntax )

### ISSUE THREAD

**Issue by pleabargain** [kolibril13/pyscript-emoji-skimage#11]
JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/site-packages/_pyodide/_base.py", line 421, in eval_code CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 237, in __init__ self.ast = next(self._gen) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 141, in _parse_and_compile_gen mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST) File "", line 1 ^ SyntaxError: invalid syntax )

I tried running as html locally.
It failed with above error.

**Comment by kolibril13** [comment]
I use the VS Code Live Server Preview, that does work.
